# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

jobs:
  - job: build_android
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
      displayName: 'Install Node.js'
    - bash: |
        npm install
      displayName: npm install
    - bash: |
        CURPWD=$(pwd)
        echo "${SIGNING_KEY}" | base64 --decode > keystore.jks
        echo "" >> android/gradle.properties
        echo "MYAPP_UPLOAD_STORE_FILE=${CURPWD}/keystore.jks" >> android/gradle.properties
        echo "MYAPP_UPLOAD_STORE_PASSWORD=${KEY_STORE_PASSWORD}" >> android/gradle.properties
        echo "MYAPP_UPLOAD_KEY_ALIAS=${ALIAS}" >> android/gradle.properties
        echo "MYAPP_UPLOAD_KEY_PASSWORD=${KEY_PASSWORD}" >> android/gradle.properties
      displayName: create android keystore
      env:
        SIGNING_KEY: $(SIGNING_KEY)
        KEY_STORE_PASSWORD: $(KEY_STORE_PASSWORD)
        ALIAS: $(ALIAS)
        KEY_PASSWORD: $(KEY_PASSWORD)
    - bash: |
        ./gradlew assembleRelease
      displayName: build
      workingDirectory: ./android
    - task: apptestai-test@0
      inputs:
        access_key: '$(APPTEST_AI_ACCESS_KEY)'
        project_id: '1103'
        binary_path: 'android/app/build/outputs/apk/release/app-release.apk'

  - job: build_ios
    pool:
      vmImage: 'macOS-latest'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
      displayName: 'Install Node.js'
    - bash: |
        npm install
        patch -u node_modules/react-native/React/Base/RCTModuleMethod.mm -i fix-xcode-11-build.patch
      displayName: npm install
    - bash: |
        fastlane beta
      displayName: build
      workingDirectory: ./ios
      env:
        APPLE_ID: $(APPLE_ID)
        TEAM_ID: $(TEAM_ID)
        APP_BUNDLE_ID: $(APP_BUNDLE_ID)
        MATCH_PASSWORD: $(MATCH_PASSWORD)
        FASTLANE_CERT_REPO: $(FASTLANE_CERT_REPO)
        MATCH_GIT_BASIC_AUTHORIZATION: $(MATCH_GIT_BASIC_AUTHORIZATION)
        MATCH_KEYCHAIN_NAME: $(MATCH_KEYCHAIN_NAME)
        MATCH_KEYCHAIN_PASSWORD: $(MATCH_KEYCHAIN_PASSWORD)
    - task: apptestai-test@0
      inputs:
        access_key: '$(APPTEST_AI_ACCESS_KEY)'
        project_id: '1102'
        binary_path: 'ios/anime_jisho.ipa'
