name: react-native CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '1.8'
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: npm install
      run: |
        npm install
    - name: create keystore file, fill key
      run: |
        CURPWD=$(pwd)
        echo "${{ secrets.SIGNING_KEY }}" | base64 --decode > keystore.jks
        echo "" >> android/gradle.properties
        echo "MYAPP_UPLOAD_STORE_FILE=${CURPWD}/keystore.jks" >> android/gradle.properties
        echo "MYAPP_UPLOAD_STORE_PASSWORD=${{ secrets.KEY_STORE_PASSWORD }}" >> android/gradle.properties
        echo "MYAPP_UPLOAD_KEY_ALIAS=${{ secrets.ALIAS }}" >> android/gradle.properties
        echo "MYAPP_UPLOAD_KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> android/gradle.properties
    - name: Build apk package
      working-directory: ./android
      run: |
        ./gradlew assembleRelease
    - name: Test app on apptest.ai
      uses: forcemax/apptestai-test@v1
      with:
        access_key: ${{ secrets.APPTEST_AI_ACCESS_KEY }}
        project_id: 1103
        binary_path: android/app/build/outputs/apk/release/app-release.apk

